/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("kotlin.custom.plugin")
}

dependencies {
    implementation(libs.bundles.exposed)
    implementation(libs.postgres.driver)
    implementation(libs.logback)
    implementation(libs.ktor.core)
}
