/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("kotlin.custom.plugin")
}

dependencies {
    implementation(libs.ktor.serialization)
    implementation(project(":infra"))
}
