/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("kotlin.custom.plugin")
    kotlin("kapt")
}

dependencies {
    implementation(libs.ktor.core)
    implementation(libs.ktor.netty)
    implementation(libs.ktor.content)
    implementation(libs.ktor.serialization)
    implementation(libs.bundles.exposed)
    implementation(libs.logback)
    implementation(libs.ktor.core)
    implementation(libs.dagger2)
    implementation(project(":database"))

    testImplementation(testLibs.kotlin.test)
    testImplementation(testLibs.mockk)

    kapt(libs.dagger2.compiler)
}

application {
    // Define the main class for the application.
    mainClass.set("com.github.takabow0705.ApiServerKt")
}
