/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.takabow0705

import com.github.takabow0705.config.DaggerApiResourceComponent
import com.github.takabow0705.config.routing.userApiRouting
import io.ktor.server.application.*
import io.ktor.server.routing.*

fun main(args: Array<String>): Unit = io.ktor.server.netty.EngineMain.main(args)

fun Application.module() {
  routing { userApiRouting(DaggerApiResourceComponent.create().userApiResource()) }
}
