/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {

}

dependencies {
    implementation(project(":domain"))
}

application {
    // Define the main class for the application.
    mainClass.set("com.github.Takabow0705.app.AppKt")
}
